[build]
  publish = "."
  command = "echo 'No build needed'"

[[headers]]
  for = "/css/*"
  [headers.values]
    Content-Type = "text/css; charset=UTF-8"

[[headers]]
  for = "/js/*"
  [headers.values]
    Content-Type = "application/javascript; charset=UTF-8"
